import { type NextPage } from "next";
import Head from "next/head";
import GameSlider from "./GameSlider";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>hbarangenc</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/lagotGames.png" />
      </Head>
      <main>
        <GameSlider></GameSlider>
      </main>
    </>
  );
};

export default Home;
