import { type NextPage } from "next";
import Head from "next/head";
import GameSlider from "./GameSlider";
import ReactPlayer from 'react-player'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>hbarangenc</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative top-50 h-full">
          <GameSlider></GameSlider>
        </div>
      </main>
    </>
  );
};

export default Home;